### ISSUE TITLE
 Connection error. Your VPC must be able to connect to Lambda and STS

### ISSUE THREAD

**Issue by mcnamara-charles** [awslabs/aws-streaming-data-solution-for-amazon-kinesis-and-amazon-msk#7]
Hello,

My team has been attempting to use your solution, specifically Option 3. We are continuously running into several issues, the primary being " PROBLEM: Connection error. Your VPC must be able to connect to Lambda and STS, as well as Secrets Manager if authentication is required. You can provide access by configuring PrivateLink or a NAT Gateway." 

This begs a few questions. Firstly, is this common and do you know how to solve it. Secondly, is Option 3 zero configuration by default?

**Comment by dscpinheiro** [comment]
Hi @mcnamara-charles!

That error message is displayed when the cluster is launched in a public (or default) subnet. Is that the setup you're using?

We actually recommend launching the Amazon MSK cluster in private subnets (where the default route points to a NAT gateway), as this networking setup is required if you plan to use AWS Lambda (this is described on the docs: https://docs.aws.amazon.com/lambda/latest/dg/services-msk-topic-add.html#services-msk-vpc-config).

On the second question, the only prerequisite for option 3 is that the topic provided as a parameter (`Name of a Kafka topic to consume`) already exists (the solution won't try to create it).

**Comment by mcnamara-charles** [comment]
We figured this out before we got this response but thank you so much for getting back to us!
